version: '3.8'

networks:
  my_app_network:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: db_c
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_app_network

  api:
    build: ./api
    container_name: api_c

    environment:
      DB_HOST: db_c
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: ${API_PORT}

    ports:
      - "${API_PORT}:${API_PORT}"

    volumes:
      - ./api:/app
    stdin_open: true
    tty: true
    networks:
      - my_app_network

  website:
    build: ./website
    container_name: website_c
    volumes:
      - ./website:/app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

    stdin_open: true
    tty: true

    networks:
      - my_app_network