#!/bin/bash

# Function to stop a container if it exists
stop_container() {
    if docker ps -a --format '{{.Names}}' | grep -Eq "^$1$"; then
        echo "Stopping container: $1"
        docker stop $1
    else
        echo "Container $1 does not exist."
    fi
}

# Check if network exists and remove it if it does
if docker network ls --format '{{.Name}}' | grep -q "^my_app_network$"; then
    echo "Removing network: my_app_network"
    docker network rm my_app_network
else
    echo "Network my_app_network does not exist."
fi

# Stop all running Docker containers
stop_container api_c
stop_container db_c
stop_container website_c

# Execute `ps aux` command and search for MySQL processes
mysql_processes=$(ps aux | grep '[m]ysqld' | awk '{print $2}')

if [ -z "$mysql_processes" ]; then
  echo "No MySQL processes running."
else
  echo "MySQL processes found:"
  echo "$mysql_processes"
  
  for pid in $mysql_processes; 
  do
    echo "Attempting to stop MySQL process with PID: $pid..."
    
    # Kill MySQL process using PID
    kill -9 $pid
    
    if [ $? -eq 0 ]; then
      echo "MySQL process with PID $pid stopped successfully."
    else
      echo "Failed to stop MySQL process with PID $pid."
    fi
  done
fi
