CREATE DATABASE IF NOT EXISTS whovians;

USE whovians;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fnmae TEXT NOT NULL,
    lname TEXT NOT NULL,
    email TEXT NOT NULL,
    cosplay BOOLEAN DEFAULT 0,
    key_hex TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS exhibs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    desc TEXT NOT NULL,
    img TEXT NOT NULL,
);
CREATE TABLE IF NOT EXISTS activities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    imgclass TEXT NOT NULL,
    img TEXT NOT NULL,
    alt TEXT NOT NULL,
    title TEXT NOT NULL,
    desc TEXT NOT NULL,
);